### PR TITLE
Fix thread-safety issue in ExceptionHelper

### PR DESCRIPTION
**Pull request by ocoanet**
One of my tests is failing non-deterministically with a `NullReferenceException` in NFluent. Here is the stack trace:
```
   at NFluent.Helpers.ExceptionHelper.ExceptionScanner()
   at NFluent.Helpers.ExceptionHelper.InitCache(String patterns)
   at NFluent.Helpers.ExceptionHelper.get_Constructors()
   at NFluent.Helpers.ExceptionHelper.BuildException(String theMessage)
   at NFluent.Kernel.ExceptionReporter.ReportError(String message)
   at NFluent.Kernel.CheckLogic`1.EndCheck()
   at NFluent.Helpers.EqualityHelper.PerformEqualCheck[T,TE](ICheck`1 check, TE expected, IEqualityComparer comparer, Boolean useOperator)
   at NFluent.DecimalCheckExtensions.IsEqualTo(ICheck`1 check, Decimal expected)
```

This exception is quite fishy because null references should not occur in `ExceptionScanner` in normal conditions. The code mutates static objects without locks, so I suspected a thread-safety issue. I looked at the `Exceptions` dictionary and it was containing a null value for NUnit even thought the code never adds null values.

NFLuentNullReferenceException

I decided to refactor the `ExceptionHelper` initialization to avoid thread-safety issues. I noticed that the `Exceptions` static dictionary was:

- Only used during `Constructors` initialization
- Always rebuild during `Constructors` initialization

There was no need to store `Exceptions` in a static field, it could be turned into a local variable.

This PR replaces the `Exceptions` field by a local variable to avoid thread-safety issues.
The change also replaces the `Patterns` parsing with simple object instantiations.

### CODE REVIEW

**Comment by dupdob** [comment]
I opened an issue for this, because we need to have a clear view of why this happens before confirming we have a fix.
By the way, current design emerged from a similar issue.
Also, note that assembly scanning can happen more than once (see `Reset` method), hence the statics. This can be discussed, as it exists today only for testing purposes.

**Comment by ocoanet** [comment]
The new code still supports resets, it just removes the unneeded static dictionary.

**Comment by dupdob** [comment]
Clear. I assumed the static variables were used to cache the assembly scan result and reused after a reset. It turns out this is not the case.
Reviewing the code, the working theory is that the race condition happens exactly while adding an entry in the dictionary, which seems very unlikely and hence should really happened rarely.
I am willing to merge this PR as is, but it would be better if you could add a regression test, as you hint you are able to do.

**Comment by ocoanet** [comment]
I added a test that fails before the PR change and passes after the change. However, the test does not generate the same error, it fails with the well known  `Collection was modified; enumeration operation may not execute`. exception. It still indicates that the PR improves the `ExceptionHelper`.

I wanted to use tasks but I switched to basic threads because I didn't want to add any package references.

Also, the test is quite slow (500 ms) but I don't know how to write fast multi-threading tests.

**Comment by ocoanet** [comment]
I found a much simpler way to reproduce the issue: simply add an `Assembly.cs` in `NFluent.Tests` with the following content:
```cs
using NUnit.Framework;

[assembly: Parallelizable(ParallelScope.Fixtures)]
[assembly: LevelOfParallelism(8)]
```

Then run all tests multiple times. You can get into different failure modes, for example:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at NFluent.Helpers.ExceptionHelper.ExceptionScanner() in C:\Dev\Sources\NFluent\code\src\NFluent\Helpers\ExceptionHelper.cs:line 111
   at NFluent.Helpers.ExceptionHelper.InitCache(String patterns) in C:\Dev\Sources\NFluent\code\src\NFluent\Helpers\ExceptionHelper.cs:line 102
```

or sometimes:
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at NFluent.Helpers.ExceptionHelper.ExceptionScanner() in C:\Dev\Sources\NFluent\code\src\NFluent\Helpers\ExceptionHelper.cs:line 109
   at NFluent.Helpers.ExceptionHelper.InitCache(String patterns) in C:\Dev\Sources\NFluent\code\src\NFluent\Helpers\ExceptionHelper.cs:line 102
   at NFluent.Helpers.ExceptionHelper.get_Constructors() in C:\Dev\Sources\NFluent\code\src\NFluent\Helpers\ExceptionHelper.cs:line 76
```

Everything works fine after the PR changes.

**Comment by ocoanet** [comment]
I can push the `Assembly.cs` file but you might not want to enable parallel tests by default. It could be added with a preprocessor directives though (e.g.: `#if ENABLE_NUNIT_PARALLELISM`).

**Pull request merged**
